# Generated by Django 2.0.7 on 2018-07-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog01', '0002_auto_20180730_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=45, verbose_name='站点名称'),
        ),
    ]
