# Generated by Django 2.0.7 on 2018-07-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog01', '0003_auto_20180731_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='site',
            field=models.CharField(default=0, max_length=45, verbose_name='站点名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=45, verbose_name='个人博客标题'),
        ),
    ]
