# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-13 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='address',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
