# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-14 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_publisher_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publish_date',
            new_name='date',
        ),
    ]
