# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=12)),
                ('pwd', models.CharField(max_length=12)),
            ],
        ),
    ]
